name: Integration Test

on:
  push:
    branches: [ enhancement/skip-tls-verification ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Self test
        id: selftest
        uses: ./
        with:
          address: ${{ secrets.ARGOCD_SERVER }}
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: sync
          appName: ${{ secrets.ARGOCD_APP_NAME }}
          image: latest
          disableTlsVerification: "false"
